version: "3"
services:
  db:
    container_name: api_tidosos
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=tidosos
      - POSTGRES_DB=data
    ports:
      - 5432:5432
